/*
 * Copyright (c) 2026 Radu Pirea
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_RESET_XLNX_ZYNQ_RESET_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_RESET_XLNX_ZYNQ_RESET_H_

/**
 * @name Xilinx Zynq-7000 reset identifiers
 *
 * A reset is identified by the control register holding it and the bit within
 * it, the registers being numbered from the first one the controller covers
 * (Zynq-7000 TRM UG585 v1.13, appendix B.28 slcr).
 *
 * @{
 */
#define XLNX_ZYNQ_RESET(bank, bit) (((bank) * 32) + (bit))

/* PSS_RST_CTRL */
#define XLNX_ZYNQ_RESET_PSS         XLNX_ZYNQ_RESET(0, 0)
/* DDR_RST_CTRL */
#define XLNX_ZYNQ_RESET_DDR         XLNX_ZYNQ_RESET(1, 0)
/* TOPSW_RST_CTRL */
#define XLNX_ZYNQ_RESET_TOPSW       XLNX_ZYNQ_RESET(2, 0)
/* DMAC_RST_CTRL */
#define XLNX_ZYNQ_RESET_DMAC        XLNX_ZYNQ_RESET(3, 0)
/* USB_RST_CTRL */
#define XLNX_ZYNQ_RESET_USB0_CPU1X  XLNX_ZYNQ_RESET(4, 0)
#define XLNX_ZYNQ_RESET_USB1_CPU1X  XLNX_ZYNQ_RESET(4, 1)
/* GEM_RST_CTRL */
#define XLNX_ZYNQ_RESET_GEM0_CPU1X  XLNX_ZYNQ_RESET(5, 0)
#define XLNX_ZYNQ_RESET_GEM1_CPU1X  XLNX_ZYNQ_RESET(5, 1)
#define XLNX_ZYNQ_RESET_GEM0_RX     XLNX_ZYNQ_RESET(5, 4)
#define XLNX_ZYNQ_RESET_GEM1_RX     XLNX_ZYNQ_RESET(5, 5)
#define XLNX_ZYNQ_RESET_GEM0_REF    XLNX_ZYNQ_RESET(5, 6)
#define XLNX_ZYNQ_RESET_GEM1_REF    XLNX_ZYNQ_RESET(5, 7)
/* SDIO_RST_CTRL */
#define XLNX_ZYNQ_RESET_SDIO0_CPU1X XLNX_ZYNQ_RESET(6, 0)
#define XLNX_ZYNQ_RESET_SDIO1_CPU1X XLNX_ZYNQ_RESET(6, 1)
#define XLNX_ZYNQ_RESET_SDIO0_REF   XLNX_ZYNQ_RESET(6, 4)
#define XLNX_ZYNQ_RESET_SDIO1_REF   XLNX_ZYNQ_RESET(6, 5)
/* SPI_RST_CTRL */
#define XLNX_ZYNQ_RESET_SPI0_CPU1X  XLNX_ZYNQ_RESET(7, 0)
#define XLNX_ZYNQ_RESET_SPI1_CPU1X  XLNX_ZYNQ_RESET(7, 1)
#define XLNX_ZYNQ_RESET_SPI0_REF    XLNX_ZYNQ_RESET(7, 2)
#define XLNX_ZYNQ_RESET_SPI1_REF    XLNX_ZYNQ_RESET(7, 3)
/* CAN_RST_CTRL */
#define XLNX_ZYNQ_RESET_CAN0_CPU1X  XLNX_ZYNQ_RESET(8, 0)
#define XLNX_ZYNQ_RESET_CAN1_CPU1X  XLNX_ZYNQ_RESET(8, 1)
/* I2C_RST_CTRL */
#define XLNX_ZYNQ_RESET_I2C0_CPU1X  XLNX_ZYNQ_RESET(9, 0)
#define XLNX_ZYNQ_RESET_I2C1_CPU1X  XLNX_ZYNQ_RESET(9, 1)
/* UART_RST_CTRL */
#define XLNX_ZYNQ_RESET_UART0_CPU1X XLNX_ZYNQ_RESET(10, 0)
#define XLNX_ZYNQ_RESET_UART1_CPU1X XLNX_ZYNQ_RESET(10, 1)
#define XLNX_ZYNQ_RESET_UART0_REF   XLNX_ZYNQ_RESET(10, 2)
#define XLNX_ZYNQ_RESET_UART1_REF   XLNX_ZYNQ_RESET(10, 3)
/* GPIO_RST_CTRL */
#define XLNX_ZYNQ_RESET_GPIO_CPU1X  XLNX_ZYNQ_RESET(11, 0)
/* LQSPI_RST_CTRL */
#define XLNX_ZYNQ_RESET_LQSPI_CPU1X XLNX_ZYNQ_RESET(12, 0)
#define XLNX_ZYNQ_RESET_QSPI_REF    XLNX_ZYNQ_RESET(12, 1)
/* SMC_RST_CTRL */
#define XLNX_ZYNQ_RESET_SMC_CPU1X   XLNX_ZYNQ_RESET(13, 0)
#define XLNX_ZYNQ_RESET_SMC_REF     XLNX_ZYNQ_RESET(13, 1)
/* OCM_RST_CTRL */
#define XLNX_ZYNQ_RESET_OCM         XLNX_ZYNQ_RESET(14, 0)
/* FPGA_RST_CTRL */
#define XLNX_ZYNQ_RESET_FPGA0_OUT   XLNX_ZYNQ_RESET(16, 0)
#define XLNX_ZYNQ_RESET_FPGA1_OUT   XLNX_ZYNQ_RESET(16, 1)
#define XLNX_ZYNQ_RESET_FPGA2_OUT   XLNX_ZYNQ_RESET(16, 2)
#define XLNX_ZYNQ_RESET_FPGA3_OUT   XLNX_ZYNQ_RESET(16, 3)
/* A9_CPU_RST_CTRL */
#define XLNX_ZYNQ_RESET_A9_CPU0     XLNX_ZYNQ_RESET(17, 0)
#define XLNX_ZYNQ_RESET_A9_CPU1     XLNX_ZYNQ_RESET(17, 1)
#define XLNX_ZYNQ_RESET_A9_CLKSTOP0 XLNX_ZYNQ_RESET(17, 4)
#define XLNX_ZYNQ_RESET_A9_CLKSTOP1 XLNX_ZYNQ_RESET(17, 5)
#define XLNX_ZYNQ_RESET_A9_PERI     XLNX_ZYNQ_RESET(17, 8)
/** @} */

/** Number of reset control registers the controller covers */
#define XLNX_ZYNQ_RESET_BANKS 18

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_RESET_XLNX_ZYNQ_RESET_H_ */
